name: Java Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Compile Java Program
        run: javac tz2_program_separate_func.java

      - name: Run Test
        run: |
          java YourProgram test1.txt 1 > program_output.txt
          diff program_output.txt test1.txt
